config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  get 'about' => 'home#about_us'
  # root 'home#index'
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except: []
  before_action :correct_user, only: [:show,:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build()
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this" if @friend.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
    @about_me = "Check about us...";
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
    <%= form_with(model: friend, local: true) do |form| %>
      <% if friend.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

          <ul>
            <% friend.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row mb-3">
        <%= form.text_field :first_name, class:"form-control",placeholder:"First Name" %>
      </div>

      <div class="row mb-3">
        <%= form.text_field :last_name, class:"form-control",placeholder:"Last Name" %>
      </div>

      <div class="row mb-3">
        <%= form.text_field :email, class:"form-control",placeholder:"E-Mail" %>
      </div>

      <div class="row mb-3">
        <%= form.text_field :phone, class:"form-control",placeholder:"Phone Number" %>
      </div>

      <div class="row mb-3">
        <%= form.text_field :twitter, class:"form-control",placeholder:"Twitter ID" %>
      </div>

      <div class="row mb-3">
        <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
      </div>

      <div class="actions">
        <%= form.submit class:"btn btn-primary" %>
      </div>
    <% end %>
 

app/views/friends/edit.html.erb
<div class="card text-dark bg-light mb-3" style="max-width: 50rem;">
  <div class="card-header">Update Friend</div>
  <div class="card-body">

        <%= render 'form', friend: @friend %>
<br>
        <%= link_to 'Show', @friend %> |
        <%= link_to 'Back', friends_path %>
    </div>
</div>

app/views/friends/index.html.erb
<h1>Friends</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user_id == current_user.id %>
        <tr>
          <td> <%= link_to friend.first_name+" "+friend.last_name, friend %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <td><%= link_to 'Edit', edit_friend_path(friend),class:"btn btn-outline-primary btn-sm" %></td>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-primary"%>

app/views/friends/new.html.erb
<div class="card text-dark bg-light mb-3" style="max-width: 50rem;">
  <div class="card-header">Add Friend</div>
  <div class="card-body">
    <%= render 'form', friend: @friend %>
<br>
    <%= link_to 'Back', friends_path %>
 </div>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <hr class="my-4">
  <p>
    <%= @friend.email %> <br>
    <%= @friend.phone %> <br>
    <%= @friend.twitter %> <br>
  </p>

  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %> 
  <%= link_to 'Back', friends_path, class:"btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Test App', root_path, class:"navbar-brand" %>
    <%# <a class="navbar-brand" href="#">Test App</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'About Us', about_path, class:"nav-link" %>
          <%# <a class="nav-link" href="#">About us</a> %>
        </li>
        
        <% if !user_signed_in? %>
        <li>
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>

          <li>
              <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
         <% end %>

        <% if user_signed_in? %>
        <li>
            <%= link_to 'Friends', friends_path, class:"nav-link" %>
        </li>
          <li>
              <%= link_to 'Sign Out', destroy_user_session_path,method: :delete, class:"nav-link" %>
          </li>

          <li>
              <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
          <% end %>


      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about_us.html.erb
<p>Sample App created using Rails...</p>

app/views/home/index.html.erb
<p>Hello World</p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render 'home/header' %> 
  <div class="container">
  <br>
  <% if notice %>
    <%= render 'layouts/alert' %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>